### PR TITLE
Add Acronym exercise

### PR DESCRIPTION
**Pull request by isaacvando**

### CODE REVIEW

**Comment by ageron** [comment]
Awesome, thanks @isaacvando!
I only have a few comments (see the code review):
* have you run `roc format` on all the `.roc` files (including `acronym-test.roc`, unfortunately it looks like the `generate_test.py` script doesn't do it, I'll fix that)? I just run `find . -name "*.roc" -exec roc format {} \;` from the project root.
* Please use `{{ case["input"]["phrase"] | to_roc }}` instead of `"{{ case["input"]["phrase"] }}"`, as it will properly handle escaping (e.g., in the `bob` exercise, one of the test cases involves a string containing `$(`, which would fail without `to_roc`.
* Please run `bin/fetch-configlet` followed by `bin/configlet fmt -u` to format the `config.json` file.

Also, I see that you've used `result = ...` and `expect result == ...`. I didn't know it made a difference, but it looks like it does display the value of `result` when a test fails, so that's great, I'll update all the other tests! 👍 

You've also included type annotations. One of the things that I like about Roc is the fact that these are totally optional, but I suppose it's best practice to include them for important / top-level functions (and when debugging)? Perhaps we could get that point across by *not* including type annotations in the stub code (i.e., `Acronym.roc`) but including type annotations in the solution (i.e., `.meta/Example.roc`), but only for top-level functions. What do you think?

**Comment by ageron** [comment]
The tweaks were fairly minor so I merged this PR and did the tweaks in PR #35
Thanks again!

**Comment by isaacvando** [comment]
Thanks for the comments and fixes @ageron!

The norm is to annotate top level definitions for readability and to improve error messages. I think at a minimum the stubs should be annotated so that it is clear to the user what types they are working with and to minimize the possibility of confusing error messages. I lean towards annotating top levels in the example solutions also, because that's usually what I do once I'm ready to polish and publish my code, but I think it's okay for there to be variation there. The example solutions seem like a better place to communicate that annotations are optional to me.

**Comment by isaacvando** [comment]
That being said, if we want the examples to be as idiomatic as possible, we should annotate top levels.

**Comment by ageron** [comment]
Thanks for your feedback, sounds good to me. I'll update the existing examples to add top-level annotations.

**Pull request merged**
