### PR TITLE
Exercise list ops Use List.append instead of List.prepend

### PR DESCRIPTION
**Pull request by ostcar**
As discussed in [zulip](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/exercism).

I also made some of the function tail recursive. Only these, that could be changed without adding helper functions.

Should I also add an explanation, why `List.append` is better in Roc then `List.prepend`? If so, where should I put it?

### CODE REVIEW

**Comment by ageron** [comment]
Looks great, thanks @ostcar . 👍 
I think a short explanation of why `List.append` is best would be great. I think you can simply add it in `instructions.append.md`.

**Comment by isaacvando** [comment]
Thanks for this @ostcar! I think it would be good to make all of the functions tail recursive with helper functions defined within the body of each one as that is a common style.

**Comment by ostcar** [comment]
I tried to add an explanation. Please have a close look. I know, that my  grammar in English is not good.

I also rewrote all functions to be tail recursive.

If the function where real, I would use `List.withCapacity` at `filter`, `map`and `reverse`. But I am not sure if this should be done in the example, since the exercise is only to use `List.append` from the builtins. What do you think?

**Review by isaacvando — APPROVED** [review]
Looks great, thanks @ostcar! I just updated the wording slightly. I think it is alright to leave List.withCapacity out of this solution.

**Pull request merged**
